import time
print ('?: Huh')
time.sleep(2)
print ('?: where am i')
time.sleep(3)
print ('?: it is cold down here')
time.sleep(1)
print ('?: like')
time.sleep(1.24)
print ('?: really cold')
time.sleep(3)
print ('you: who are-')
time.sleep(0.25)
print ('?: wy8yab9arvsugyb')
time.sleep(0.25)
print ('?: 9erqfhyqfqwhefh')
time.sleep(0.25)
print ('?: rueq90qerq0rf')
time.sleep (1)
print ('?: holy shit you scared me')
time.sleep(1.75)
print ('?: wait')
time.sleep(3.5)
print ('?: who the hell are')
time.sleep(2)
print ('(no seriously, who the hell are you?)')
PlayerName = input()
print (PlayerName +'?')
time.sleep(2)
print ('?: wow')
time.sleep(2)
print ('?: that name is a stupid ass name xD')
time.sleep(1)
print ('?: Major')
time.sleep(2)
print (Playername + ': what?')
time.sleep(2)
print ('?: My name is Major')
time.sleep(2)
print ('Major: Major Baby')
time.sleep(2)
print ('Major. friends call me May May')
time.sleep(2.8)
print ('Major: i got turned into a fucking dog man')
time.sleep(1)
print ('damn witch')
time.sleep(1)
print ('she turned my mom into a dog 2 months into pregancy')
print (PlayerName +'who?')
time.sleep(5)
print ('Major: Black Kitty')
time.sleep(0.3)
print ('2 new portraits unlocked')
print ('portraits will be accessible in the folder named "Portraits" in the full game')

