#by www.youtube.com/OmegaGamerLol
MaybePeopleWillSeeThisAndThinkItsAnEasterEggButRealizeItsNot = 1
Altf4 = MaybePeopleWillSeeThisAndThinkItsAnEasterEggButRealizeItsNot
import time
import random
import sys
file = open('item_ids.underground')
content = file.readlines()
gamestart = int(content[4])
Player_Health = 100
Monster_Health = 91108
ItemSlot = 'hand'
Coins = 0
key = int(0)
skip = input('Skip first texted sequence? (y/n) ')
if skip == 'n':
  time.sleep(3)
  print("*splash*\n")
  time.sleep(3.5)
  print('?: Huh')
  time.sleep(2)
  print('?: where am i')
  time.sleep(3)
  print('?: it is cold down here')
  time.sleep(1.5)
  print('?: like')
  time.sleep(1.84)
  print('?: purty cold')
  time.sleep(3)
  print('?: It must be October 3rd') 
  time.sleep(2)
  print('?: hmmmm')
  time.sleep(4)
  print('?: the only place that has wells are fyretown and jurgag.')
  time.sleep(7)
  print('?: and if im in fyretown there should be a key to get out')
  time.sleep(6)
  print('?: if this is Jurgag id be better off a deer in a hunting competition')
  time.sleep(6.5)
  print('?: If only I had someone down here with me; this would be a whole lot easier')
  time.sleep(6)
  print('you: who are-')
  time.sleep(2.5)
  print('?: christ on a stick you scared me')
  time.sleep(2)
  print('?: wait')
  time.sleep(3.5)
  print('?: who are you')
  time.sleep(4)
  print('(no seriously, who are you?)')
  PlayerName = input()
  if PlayerName == 'Im9YearsOld':
    print('Omega: garbage name')
  else:
    time.sleep(1)
    print('?:' + PlayerName + '?')
    time.sleep(1)
  if PlayerName == 'altf4':
    print('Omega: Ok your wish is my command')
    time.sleep(3)
    print('?: Wait who said that?!')
    time.sleep(3)
    print('Omega: ...')
    time.sleep(5)
    print('?: Cowlick on a baby who are you?!!')
    time.sleep(5)
    print('*footsteps*')
    time.sleep(2)
    print('?: Wait! Dont touch that.')
    time.sleep(5)
    print('*Rumble*')
    time.sleep(3)
    print('Omega: Shouldnt have typed altf4 ¯\_(ツ)_/¯. If you lose this fight I destroy this galaxy')
    time.sleep(8)
    print('you: what if I win')
    time.sleep(3)
    print('Omega: Then I dont destroy it')
    time.sleep(4.5)
    print('you: well thats just not fair')
    time.sleep(5)
    print('Omega: Thats too bad...')
    time.sleep(4)
    print('you: ...')
    time.sleep(5)
    print('⚐︎❍︎♏︎♑︎♋︎ has appeared')
    time.sleep(4)
    while Monster_Health > 0:
      if Player_Health < 1:
        print('Omega: well that was pathetic...')
        time.sleep(5)
        print('you: I- I-')
        time.sleep(2)
        print('You died')
        time.sleep(2)
        sys.exit()
      else:
        print ('Type 1 to use your item: ' + str(ItemSlot) +  ' | Your HP: ' +  str(Player_Health) + ' | ⚐︎❍︎♏︎♑︎♋︎ HP: ' + str(Monster_Health) )
      Fight_1 = input()
      if Fight_1 < '2':
        Damage = random.randint(1, 2)
        critical = random.randint(1, 20)
        Monster_Health = Monster_Health - Damage
        if critical == 13:
          Monster_Health = Monster_Health - 20%Damage
          time.sleep(2)
          print ('You landed a critcal hit!(adds 20% more damage to your total damage)\n')
        time.sleep(3)
        if Monster_Health < 0:
          print ( 'Your HP: ' +  str(Player_Health) + ' | Opponent HP: DEAD')
        else:
          print ( 'Your HP: ' +  str(Player_Health) + ' | Opponent HP: ' + str(Monster_Health) )
        time.sleep (2)
      print('⚐︎❍︎♏︎♑︎♋︎ uses ☜︎♎︎♑︎⍓︎ ⧫︎♏︎⌧︎⧫︎ ❍︎♏︎♋︎■︎⬧︎ ♑︎□︎□︎♎︎ ♋︎⧫︎⧫︎♋︎♍︎🙵 ♓︎ ⧫︎♒︎♓︎■︎🙵\n')
      MDamage = random.randint(384, 500)
      critical = random.randint(7, 13)
      time.sleep (1)
      Player_Health = Player_Health - MDamage
      time.sleep (1)
      if critical == 13:
        Player_Health = Player_Health - 20%MDamage
        print ('⚐︎❍︎♏︎♑︎♋︎ landed a critical hit!(adds 20% more damage to your total damage)\n')
        time.sleep(2)
      else: 
        time.sleep(1)
      print ( str(PlayerName) + ' is now at ' + str(Player_Health) + ' ☜︎♎︎♑︎⍓︎ ⧫︎♏︎⌧︎⧫︎ ❍︎♏︎♋︎■︎⬧︎ ♑︎□︎□︎♎︎ ♋︎⧫︎⧫︎♋︎♍︎🙵 ♓︎ ⧫︎♒︎♓︎■︎🙵  does ' + str(MDamage) + ' damage!\n')
  else:
#end
    
    print('?: Major')
  time.sleep(2)
  print(PlayerName + ': what?')
  time.sleep(2)
  print('?: My name is Major')
  time.sleep(2)
  print('Major: Major Baby')
  time.sleep(2)
  print('Major: friends call me May May')
  time.sleep(2.8)
  print('Major: i got turned into a frickin dog!')
  time.sleep(4)
  print('Major: the witch')
  time.sleep(1.5)
  print('Major: she turned my mom into a dog 2 months into pregancy')
  time.sleep(4)
  print(PlayerName + ': who?')
  time.sleep(4)
  print('Major: Black Kitty')
  time.sleep(2)
  print(PlayerName + ': who is tha-')
  time.sleep(1.2)
  print('Major: not important')
  time.sleep(3)
  print('Major: anyways here is a rock')
  time.sleep(2.8)
  print(PlayerName + ': what? why would I need that?')
  time.sleep(3)
  print ('Major: I need you to hunt down some Lesser Mama Kitties. Keep hunting until one drops a key. I saw one with a key. Find one in the basement')
else:
  time.sleep(2)
  if skip == 'y':
    PlayerName = input('What is your name? ')
    if PlayerName == 'altf4':
      print('Omega: Ok your wish is my command ¯\_(ツ)_/¯')
      time.sleep(3)
      sys.exit()
    if PlayerName == 'BirthdayBoy':
      BB = input('W who is the goodest dog?\n')
      if BB == 'Majorbaby' or 'Major' or 'MayMay':
        print('Correct!')
        gamestart = gamestart + gamestart + gamestart + 1
      else:
        print('>:(')
  print ('Major: I need you to hunt down some Lesser Mama Kitties. Keep hunting until one drops a key. I saw one with a key. Find one in the basement')
time.sleep(5)
print('Quest unlocked: The Wells basement')
#Second half
#declaring varibles for later use
import time
import math
import random
Monster = random.randint(1, 1000)
Hunt = 69420
Rock = 'Rock'
Damage = 0
#bad coding skill mistake L
#def var 'Player_Health'
#def var 'Monster_= Health'
Monster_Health = int(100)
if PlayerName == 'W':
 PlayerName = 'L'
if PlayerName == 'Im9YearsOld':
  PlayerName = 'IAmRetarded'
  ItemSlot = 'Retard_Stick'
else:
  Player_Health = int(100)
  ItemSlot = Rock
time.sleep(3)

print ('Hunt for Lesser Mama Kitty and find a key \n')
print ('To continue type "c"\n')
print ('For monster info type "i"\n')
Hunt = input()
if Hunt == 'i':
  
  print ('Lesser Mama Kitties are weaker versions of Mama Kitty and much weaker versions of Greater Mama Kitties. Lesser Mama Kitties have 100 Hit points (HP) which is equal to that of the     player ('  + str(PlayerName) + ') with no items. They have a 3/10 chance of spawning. This is the tutorial monster. Fun Fact: a picture of Mama Kitty can be found in the files\n') 
  time.sleep(23)
  print ('Hunt for Lesser Mama Kitty and find a key\n')
print ('Hunt for monster with "h"\n')
Hunt = input()
while Monster < 700:
  Monster = random.randint(1, 1000)
if Monster < 700:
    while Monster < 700:
      print ('Rehunting (found nothing)...')
    time.sleep(2)
    Monster += 1  
else:
    if Monster > 700:
      print('You ran into a(n) Lesser Mama Kitty\n')
    time.sleep(3)
#turn 1
while Monster_Health > 0:
  print ('Type 1 to use your item: ' + str(ItemSlot) +  ' | Your HP: ' +  str(Player_Health) + ' | Opponent HP: ' + str(Monster_Health) )
  Fight_1 = input()
  if Fight_1 < '2':
    Damage = random.randint(16, 20)
    critical = random.randint(1, 20)
    Monster_Health = Monster_Health - Damage
    if critical == 13:
      Monster_Health = Monster_Health - 20%Damage
      time.sleep(2)
      print ('You landed a critcal hit!(adds 20% more damage to your total damage)\n')
    time.sleep(3)
    if Monster_Health < 0:
      print ( 'Your HP: ' +  str(Player_Health) + ' | Opponent HP: DEAD')
    else:
      print ( 'Your HP: ' +  str(Player_Health) + ' | Opponent HP: ' + str(Monster_Health) )
    time.sleep (2)
  print('The Lesser Mama Kitty uses her claws\n')
  MDamage = random.randint(5, 15)
  critical = random.randint(1, 20)
  time.sleep (1)
  Player_Health = Player_Health - MDamage
  time.sleep (1)
  if critical == 13:
    Player_Health = Player_Health - 20%MDamage
    print ('The Lesser Mama Kitty landed a critical hit!(adds 20% more damage to your total damage)\n')
    time.sleep(2)
  else: 
    time.sleep(1)
  print ( str(PlayerName) + ' is now at ' + str(Player_Health) + ' | Lesser Mama Kitty does ' + str(MDamage) + ' damage!\n')
#end
key = 1
if key == 1:
  print('You beat Lesser Mama Kitty. You earned 10 coins and a ' + 'Key')
  Coins = Coins + 10
  
if key != 1:
  print('You beat Lesser Mama Kitty. You earned 10 coins')
  Coins = Coins + 10
time.sleep(2)
#choice1
if key == 1:
  choice1 = input(' Talk to Major with "T".')
  time.sleep(2)
  if choice1 == 't':
    if key == 1:
      print('Major: You got it?')
      time.sleep(2)
      print(PlayerName + ': Yes')
      time.sleep(2)
      print('Major: Gimme that')
      time.sleep(2)
      print('Major:You really did it! nice')
      time.sleep(2)
      print('______________________________________')
      print('|                                    |')
      print('|                                    |')
      print('|                                    |')
      print('|                                    |')
      print('|                                    |')
      print('|                                    |')
      print('|                                    |')
      print('|                                    |')
      print('|                                    |')
      print('|                               (0)  |')
      print('|                                    |')
      print('|                                    |')
      print('|                                    |')
      print('|                                    |')
      print('|                                    |')
      print('|                                    |')
      print('|                                    |')
      print('|                                    |')
      print('|                                    |')
      print('|                                    |')
      print('--------------------------------------')
      Door = 1
      if Door == 1:
        time.sleep(0.25)
        print('\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n') 
        print('_____________________________         ')
        print('|                            -----    ')
        print('|                                  --|')
        print('|                                    |')
        print('|                                    |')
        print('|                                    |')
        print('|                                    |')
        print('|                                    |')
        print('|                                    |')
        print('|                                    |')
        print('|                               (0)  |')
        print('|                                    |')
        print('|                                    |')
        print('|                                    |')
        print('|                                    |')
        print('|                                    |')
        print('|                                    |')
        print('|                                    |')
        print('|                                    |')
        print('|                                  --|')
        print('|                              ----   ')
        print('-------------------------------       ')
        time.sleep(0.25)
        print('\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n')
        print('_________________________             ')
        print('|                        ------       ')
        print('|                               ----  ')
        print('|                                   -|')
        print('|                                    |')
        print('|                                    |')
        print('|                                    |')
        print('|                                    |')
        print('|                                    |')
        print('|                                    |')
        print('|                               (0)  |')
        print('|                                    |')
        print('|                                    |')
        print('|                                    |')
        print('|                                    |')
        print('|                                    |')
        print('|                                    |')
        print('|                                    |')
        print('|                                   -|')
        print('|                               ----  ')
        print('|                         ------      ')
        print('--------------------------            ')
        time.sleep(0.25)
        print('\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n')
        print('________________             ')
        print('|               ------       ')
        print('|                      -----|')
        print('|                           |')
        print('|                           |')
        print('|                           |')
        print('|                           |')
        print('|                           |')
        print('|                           |')
        print('|                           |')
        print('|                      0    |')
        print('|                           |')
        print('|                           |')
        print('|                           |')
        print('|                           |')
        print('|                           |')
        print('|                           |')
        print('|                           |')
        print('|                           |')
        print('|                      -----|')
        print('|                ------      ')
        print('-----------------            ')
        time.sleep(0.5)
        print('\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n')
        print('_______             ')
        print('|      ------       ')
        print('|             -----|')
        print('|                  |')
        print('|                  |')
        print('|                  |')
        print('|                  |')
        print('|                  |')
        print('|                  |')
        print('|                  |')
        print('|             )    |')
        print('|                  |')
        print('|                  |')
        print('|                  |')
        print('|                  |')
        print('|                  |')
        print('|                  |')
        print('|                  |')
        print('|                  |')
        print('|             -----|')
        print('|       ------      ')
        print('--------            ')
        time.sleep(0.25)
        print('\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n')
        print('___            ')
        print('|  -----       ')
        print('|        -----|')
        print('|             |')
        print('|             |')
        print('|             |')
        print('|             |')
        print('|             |')
        print('|             |')
        print('|             |')
        print('|           . |')
        print('|             |')
        print('|             |')
        print('|             |')
        print('|             |')
        print('|             |')
        print('|             |')
        print('|             |')
        print('|             |')
        print('|        -----|')
        print('|   -----      ')
        print('---            ')
        time.sleep(0.25)
        print('\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n')
        print('_            ')
        print('| ---       ')
        print('|    ---|')
        print('|       |')
        print('|       |')
        print('|       |')
        print('|       |')
        print('|       |')
        print('|       |')
        print('|       |')
        print('|       |')
        print('|       |')
        print('|       |')
        print('|       |')
        print('|       |')
        print('|       |')
        print('|       |')
        print('|       |')
        print('|       |')
        print('|    ---|')
        print('| ---      ')
        print('-            ')
        print('\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n')
        time.sleep(6.5)
        print('\033[1;32mRistie Cridgeway has appeared!')
        time.sleep(9)
        print('End of demo!')
        time.sleep(10)
        print('Well bye')
        time.sleep(5)
        print('Im just gonna...')
        time.sleep(3)
        print('uhh')
        time.sleep(3)
        sys.exit()
  else:
    if gamestart is not int(91108):
      print('Error69: you are gay')
      time.sleep(3)
      sys.exit()
    if choice1 == int(gamestart):
      print('well good job')
      time.sleep(3)
      print('watchu want a cookie xD')
      time.sleep(4)
      print('well here you go for your troubles')
      time.sleep(5)
      print('10322')
      time.sleep(8)
      print('get out of my shed the way you hunt for easter eggs, the determination-')
      time.sleep(7.2)
      print('quite frankly...')
      time.sleep(3)
      print('it makes me sick')
      time.sleep(3)
      print('*slam*')
      time.sleep(2)
      sys.exit()
